theme: jekyll-theme-minimal
title: Ginga Dating Sim
description: Currently under construction.
favicon: "assets/window_icon.png"
image: "assets/window_icon.png"
twitter: "silverfangnet"
show_downloads: false
